<?php

/**
 * @file
 * Contains libcal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

define("LIBCAL_UTSC_CALID", 2021);

/**
 * Implements hook_help().
 */
function libcal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the libcal module.
    case 'help.page.libcal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is integrate Libcal API and feed to drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function libcal_theme() {
  return [
    'libcal' => [
      'render element' => 'children',
    ],
  ];
}

function libcal_cron() {
  print_log("execute download data from LibCal automatically");
  // setup cron job:
  // crontab -e
  // add   0 8 * * * curl http://d9.dsu-pp.server.utsc.utoronto.ca/cron/ax9hjCCI4_fIw5WkG7RSJ0bykbMiqjHdKP_SFpvjm7L0tAF6pJW3acLoSameWkKfNl7Ehf1btg at 8 a.m daily
  // add   0 * * * * curl {{ cron URL }} at every 1 hour
  // add   0 0 * * 0 curl {{ cron URL }} at every week
  // add   0 0 1 * * curl {{ cron URL }} at every month

  $service = \Drupal::service('libcal.download');
  $result = $service->get("events?cal_id=7288")->events;
  //$result = $service->get("events?cal_id=". LIBCAL_UTSC_CALID)->events;

  // process event data to Event nodes
  $service->libcalEventToNode($result);
}

/**
 * Debug function: display any variable to error log
 *
 * @param $thing
 */
function print_log($thing)
{
  error_log(print_r($thing, true), 0);
}

/**
 * Debug function: display any variable to current webpage
 * @param $thing
 */
function logging($thing)
{
  echo "<pre>";
  print_r($thing);
  echo "</pre>";
}
